### ISSUE TITLE
Error installing on Windows

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin-plugin-isomounter#4]
So apparently the plugin installed fine but when I checked the logs I saw there was an error and the plugin shows version 0.0.0.0, this is what I got on the log when I try to unisntall the plugin:

```
System.UnauthorizedAccessException: Access to the path 'Jellyfin.Plugin.IsoMounter.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.UninstallPlugin(IPlugin plugin)
   at MediaBrowser.Api.PluginService.Delete(UninstallPlugin request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

I'm using latest stable on Windows 10, the same happened with latest unstable.

**Comment by crobibero** [comment]
On windows you have to stop jellyfin, remove the old plugin, then install the updated version.

**Comment by 1024mb** [comment]
I didn't had the plugin installed, this was the first time installing the plugin, on the notification log in the dashboard I got a message saying that the plugin was successfully installed, then followed by that an error on updating the plugins.

Btw, this line `System.UnauthorizedAccessException: Access to the path 'Jellyfin.Plugin.IsoMounter.dll' is denied.` has appeared for the Trakt plugin also, of course with the Ismounter.dll part changed to Trakt.dll. I had to delete the folder manually to uninstall both plugins.

**Comment by 1024mb** [comment]
I still can't install the plugin on 10.6.2, Trakt installed and works well, this plugin on the other hand I can't install it, I keep getting the same error.

```
Access to the path 'Jellyfin.Plugin.IsoMounter.dll' is denied. at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel) at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive) at System.IO.Directory.Delete(String path, Boolean recursive) at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by oddstr13** [comment]
Looks like the 0.0.0.0 version number is due to using the old AssemblyInfi.cs mechanism.

https://github.com/jellyfin/jellyfin-plugin-isomounter/blob/f3001ac69de89ed930765412b5bc03a84c2087e3/src/Jellyfin.Plugin.IsoMounter/Jellyfin.Plugin.IsoMounter.csproj#L7

https://github.com/jellyfin/jellyfin-plugin-isomounter/blob/f3001ac69de89ed930765412b5bc03a84c2087e3/src/Jellyfin.Plugin.IsoMounter/Properties/AssemblyInfo.cs

As for Windows support, I don't see any code dealing with iso mounting on Windows, only Linux.

**Comment by 1024mb** [comment]
> 
> 
> Looks like the 0.0.0.0 version number is due to using the old AssemblyInfi.cs mechanism.
> 
> https://github.com/jellyfin/jellyfin-plugin-isomounter/blob/f3001ac69de89ed930765412b5bc03a84c2087e3/src/Jellyfin.Plugin.IsoMounter/Jellyfin.Plugin.IsoMounter.csproj#L7
> 
> [`f3001ac`/src/Jellyfin.Plugin.IsoMounter/Properties/AssemblyInfo.cs](https://github.com/jellyfin/jellyfin-plugin-isomounter/blob/f3001ac69de89ed930765412b5bc03a84c2087e3/src/Jellyfin.Plugin.IsoMounter/Properties/AssemblyInfo.cs)
> 
> As for Windows support, I don't see any code dealing with iso mounting on Windows, only Linux.


I thought JF failing to install this plugin was the cause of ISO playback not working on a WebOS client but if this plugin doesn't work on Windows I guess it is not.
Thanks for taking a look at this.
